code --install-extension apollographql.vscode-apollo
code --install-extension bierner.markdown-mermaid
code --install-extension bradlc.vscode-tailwindcss
code --install-extension britesnow.vscode-toggle-quotes
code --install-extension catppuccin.catppuccin-vsc
code --install-extension christian-kohler.path-intellisense
code --install-extension csharpier.csharpier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension dotenv.dotenv-vscode
code --install-extension drilko.fastendpoints
code --install-extension eamodio.gitlens
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.remotehub
code --install-extension github.vscode-github-actions
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-syntax
code --install-extension heybourn.headwind
code --install-extension humao.rest-client
code --install-extension johnpapa.vscode-peacock
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mylesmurphy.prettify-ts
code --install-extension netcorext.uuid-generator
code --install-extension orta.vscode-jest
code --install-extension ow.vscode-subword-navigation
code --install-extension pkief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension svelte.svelte-vscode
code --install-extension tal7aouy.icons
code --install-extension unifiedjs.vscode-mdx
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vunguyentuan.vscode-css-variables
code --install-extension wayou.vscode-todo-highlight
code --install-extension yoavbls.pretty-ts-errors
code --install-extension zignd.html-css-class-completion